---
- name: browse-all
  hosts: all
  become: true
  tasks:
    - name: Check Kubelet status
      ansible.builtin.shell: systemctl status kubelet | grep Active
      register: kubelet_status
      ignore_errors: yes
      
    - name: Verify KC_monitor_agent Installation
      ansible.builtin.shell: systemctl status kic_monitor_agent | grep Active
      register: kc_monitor_agent_status
      ignore_errors: yes

    - name: Verify KC Node Exporter Installation
      ansible.builtin.shell: systemctl status node_exporter | grep Active
      register: kc_node_exporter_status
      ignore_errors: yes
  
    - name: Check MySQL status
      ansible.builtin.shell: systemctl status mysql | grep Active
      register: mysql_status
      when:
        "'databases' in group_names"
      ignore_errors: yes

    - name: KC Monitor Agent Status
      ansible.builtin.debug:
        var: kc_monitor_agent_status.stdout_lines

    - name: KC Node Exporter Status
      ansible.builtin.debug:
        var: kc_node_exporter_status.stdout_lines

    - name: Kubelet Status Output
      ansible.builtin.debug:
        var: kubelet_status.stdout_lines
      when: 
        "'kubernetes' in group_names"

    - name: MySQL Status Output
      ansible.builtin.debug:
        var: mysql_status.stdout_lines
      when: 
        "'databases' in group_names"