---
- name: Install Grafana
  hosts: all
  become: true
  tasks:
    - name: update package
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400
    - name: install list of packages for Grafana
      ansible.builtin.apt:
        pkg:
        - apt-transport-https
        - software-properties-common
        - wget
    - name: create directory to store Grafana GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings/
        state: directory
        mode: 0757
    - name: download Grafana GPG key
      shell: wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null
    - name: add Grafana APT repository
      shell: echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
    - name: Update repositories cache and install "grafana" package
      ansible.builtin.apt:
        name: grafana
        update_cache: yes
    - name: start Grafana
      ansible.builtin.systemd:
        state: restarted
        name: grafana-server
    - name: enable Grafana
      ansible.builtin.systemd:
        name: grafana-server
        enabled: true
    - name: verify Grafana installation
      ansible.builtin.shell: systemctl status grafana-server | grep Active
      register: grafana_status
      ignore_errors: true
    - name: display grafana status
      ansible.builtin.debug:
        var: grafana_status.stdout_lines


