global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  # - "first.rules"
  # - "second.rules"
scrape_configs:
  - job_name: 'public-dktechin-shared'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.200.4.198:9090'] 
        labels:
          vpc:  'vpc-prod-shared'
          subnet: 'sub-prod-pri-shared-a'
          host_name: 'shared-prod-prometheus'
          service: 'prometheus'
          type: 'vm'
      - targets: ['10.200.4.198:9100']
        labels:
          vpc:  'vpc-prod-shared'
          subnet: 'sub-prod-pri-shared-a'
          host_name: 'shared-prod-prometheus'          
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.200.0.45:9100']
        labels:
          vpc: 'vpc-prod-shared'
          subnet: 'sub-prod-pub-shared-a'
          host_name: 'shared-prod-nat'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.200.0.176:9100']
        labels:
          vpc: 'vpc-prod-shared'
          subnet: 'sub-prod-pub-shared-a'
          host_name: 'shared-prod-gw'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.200.4.241:9100']
        labels:
          vpc: 'vpc-prod-shared'
          subnet: 'sub-prod-pri-shared-a'
          host_name: 'shared-prod-IaC'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.200.4.81:9100']
        labels:
          vpc: 'vpc-prod-shared'
          subnet: 'sub-prod-pri-shared-a'
          host_name: 'shared-prod-grafana'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.200.0.70:9100'] 
        labels:
          vpc: 'vpc-prod-shared'
          subnet: 'sub-prod-pri-shared-a'
          host_name: 'shared-prod-bastion'
          service: 'node-exporter'
          type: 'vm'  

  - job_name: 'public-dktechin-connect_message'
    scrape_interval: 5s
    static_configs:
      - targets: ['210.109.52.47:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pub-kicm-a'
          host_name: 'kicm-csp-prod-fia-bastion-01'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['210.109.52.186:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pub-kicm-a'
          host_name: 'kicm-csp-prod-fia-nat-01'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.185:9100']
        labels:
          vpc:  'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-redis-01'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.44:9100']
        labels:
          vpc:  'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-redis-02'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.151:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-redis-03'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.72:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-rabbitmq-01'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.199:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-rabbitmq-02'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.109:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-rabbitmq-03'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.65:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-api-01'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.89:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-api-02'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.108:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-agent-01'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.159:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-agent-02'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.168:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-group-01'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.198:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-group-02'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.241:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-gw-01'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.204:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-gw-02'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.61:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-support-01'
          service: 'node-exporter'
          type: 'vm'
      - targets: ['10.203.68.107:9100']
        labels:
          vpc: 'vpc-csp-prod-kicm'
          subnet: 'sub-csp-prod-pri-kicm-a'
          host_name: 'kicm-csp-prod-fia-manager-01'
          service: 'node-exporter'
          type: 'vm'                                        