---
- name: browse-all
  hosts: all
  become: true
  tasks:
    - name: Check disk usage and grep for /dev/vda1
      ansible.builtin.shell: df -h | grep /dev/vda1
      register: disk_usage
    
    - name: Disk Usage Output
      ansible.builtin.debug:
        var: disk_usage.stdout_lines
    
    - name: Check memory usage
      ansible.builtin.shell: free -h
      register: mem_usage
    
    - name: Memory Usage Output
      ansible.builtin.debug:
        var: mem_usage.stdout_lines

    - name: Check Kubelet status
      ansible.builtin.shell: systemctl status kubelet | grep Active
      register: kubelet_status
      ignore_errors: yes

    - name: Kubelet Status Output
      ansible.builtin.debug:
        var: kubelet_status.stdout_lines
      when: 
        "'kubernetes' in group_names"

    - name: Verify KC_monitor_agent Installation
      ansible.builtin.shell: systemctl status kic_monitor_agent | grep Active
      register: kc_monitor_agent_status

    - name: KC Monitor Agent Status
      ansible.builtin.debug:
        var: kc_monitor_agent_status.stdout_lines

    - name: Verify KC Node Exporter Installation
      ansible.builtin.shell: systemctl status node_exporter | grep Active
      register: kc_node_exporter_status
      ignore_errors: yes

    - name: KC Node Exporter Status
      ansible.builtin.debug:
        var: kc_node_exporter_status.stdout_lines

    - name: Check MySQL status
      ansible.builtin.shell: systemctl status mysql | grep Active
      register: mysql_status
      when:
        "'databases' in group_names"
      ignore_errors: yes


    - name: MySQL Status Output
      ansible.builtin.debug:
        var: mysql_status.stdout_lines
      when: 
        "'databases' in group_names"