---
- name: U01-disableRootLogin
  hosts: all
  become: true

  tasks:
    - name: Disable Root Login
      lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: "PermitRootLogin no"
            state: present
            backup: yes
      notify:
        - restart ssh
    - name: check ssh status
      shell: systemctl status sshd
      register: sshd_status

    - name: display output of sshd status
      ansible.builtin.debug:
        var: sshd_status.stdout_lines

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
