---
- name: U01-disableRootLogin
  hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: Enable Root Login
      lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: "PermitRootLogin no"
            state: present
            backup: yes
      notify:
        - restart ssh

  handlers:
  - name: restart ssh
    service:
      name: sshd
      state: restarted
