---
- name: U01-disableRootLogin
  hosts: all
  become: true

  tasks:
    - name: Disable Root Login
      lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: "PermitRootLogin no"
            state: present
            backup: yes
      notify:
        - restart ssh

    - name: check sshd status
      shell: systemctl status sshd
      register: sshd_status

    - name: check ssh config
      shell: cat /etc/ssh/sshd_config | grep -i permitrootlogin
      register: ssh_config_status

    - name: display output of sshd status
      ansible.builtin.debug:
        msg: "{{ sshd_status }}"
      when: "'running' not in sshd_status.stdout"

    - name: display output of ssh config status
      ansible.builtin.debug:
        var: ssh_config_status.stdout_lines

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
