---
- name: modify-all
  hosts: all
  become: true
  tasks:
    - name: INSTALL KC MONITOR_AGENT
      ansible.builtin.script: /etc/ansible/scripts/kc_monitor_agent.sh

    - name: INSTALL KC NODE_EXPORTER
      ansible.builtin.script: /etc/ansible/scripts/kc_node_exporter.sh

    - name: INSTALL MYSQL NODE_EXPORTER
      ansible.builtin.script: /etc/ansible/scripts/mysqld_node_exporter.sh
      when:
        "'databases' in group_names"