---
- hosts: all
  become: yes
  vars:
    nfsmounts:
      - {  path: "/data1", src: "10.203.68.91:/kicm-csp-prod-fia-nfs-01" }
  tasks:
      - name: mount the nfsshare in client side
        mount:
          fstype: nfs4
          opts: defaults
          dump: '0'
          passno: '0'
          state: mounted
          src: "{{ item.src }}"
          path: "{{ item.path }}"
        with_items: "{{ nfsmounts }}"