---
- name: early bird testing
  hosts: all
  become: true
  tasks:
  # - name: Get stats of a file
  #   ansible.builtin.stat:
  #     path: /home/ubuntu/ansible.test
  #   register: ante
  # - name: touch file
  #   ansible.builtin.file:
  #     path: /home/ubuntu/ansible.test
  #     state: touch
  # - name: debug result
  #   ansible.builtin.debug:
  #     msg: "created"
  #   when: not ante.stat.exists
   - name: Verify KC_monitor_agent Installation
     ansible.builtin.shell: systemctl status kic_monitor_agent | grep Active
     register: kc_monitor_agent_status
     ignore_errors: yes

   - name: Check if Service Exists(DEP Verify KC_monitor_agent Installation)
       stat: path=/lib/systemd/system/kic_monitor_agent.service
       register: kc_monitor_agent

   - name: KC Monitor Agent Status
     service_facts:
   - ansible.builtin.debug:
       var: kc_monitor_agent_status.stdout_lines
     when: 
       not kc_monitor_agent.stat.exists
