---
- name: create user for ansible
  hosts: centos
  become: true
  vars:
    users:
      - "ansible"
  tasks:
    - name: "Create user accounts"
      user:
        name: "{{ item }}"
        groups: "wheel"
        shell: /bin/bash
        password: "{{ 'ansible' | password_hash('sha512') }}"
      with_items: "{{ users }}"
    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', '/etc/ansible/'+ item + '.key.pub') }}"
      with_items: "{{ users }}"